### ISSUE TITLE
Secondary loopback IP via systemd-network

### ISSUE THREAD

**Issue by bugsyb** [systemd/systemd#14903]
**Used distribution**
 > …
Ubuntu 18.04.3 LTS => systemd-networkd renderer

**Expected behaviour you didn't see**
Secondary loopback IP from space of `127.0.0.5/8`.
Choosing any other IP, i.e. `12.34.56.78/32` works fine for lo too.
Secondary IP is required for getting loopback only service/port open, which can't be exposed on any other interface and port on `127.0.0.1` is occupied already.

**Unexpected behaviour you saw**
Message: 
`lo: could not set address: Invalid argument`
And lack of getting IP configured.

**Steps to reproduce the problem**
Get lo.yaml:
```
Config:
network:
  version: 2
  renderer: networkd
  ethernets:
    lo:
      match:
        name: lo
      addresses:
        - 127.0.0.1/8
        - 127.0.0.5/8

```
`netplan generate && netplan apply
`
Gets `/run/systemd/network/10-netplan-lo.network `
```
[Match]
Name=lo

[Network]
LinkLocalAddressing=ipv6
Address=127.0.0.1/8
Address=127.0.0.5/8

```
But fails with message as reported.
Equally running "`ip addr add 127.0.0.5/8 dev lo`" works perfectly fine and gets to the goal.
