### ISSUE TITLE
systemd-networkd fails to add vlan interfaces to bond at boot time

### ISSUE THREAD

**Issue by jaymzmac** [systemd/systemd#15280]
**systemd version the issue has been seen with**
> systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

**Expected behaviour you didn't see**
 > Expected to have a bond interface with 2 vlan interfaces (enp179s0f0.324 and enp179s0f1.324) added as slaves.

**Unexpected behaviour you saw**
 >systemd-networkd[1641]: enp179s0f0.324: Enslaving by 'bond0’
systemd-networkd[1641]: bond0: Enslaving link 'enp179s0f0.324’
systemd-networkd[1641]: enp179s0f1.324: Enslaving by 'bond0’
systemd-networkd[1641]: bond0: Enslaving link 'enp179s0f1.324’
systemd-networkd[1643]: enp179s0f1.324: Could not join netdev: Operation not permitted
systemd-networkd[1643]: enp179s0f1.324: Failed
systemd-networkd[1643]: enp179s0f0.324: Could not join netdev: Operation not permitted
systemd-networkd[1643]: enp179s0f0.324: Failed

**Steps to reproduce the problem**

Simply reboot with the following netplan config file in place.

```
network:
  version: 2
  renderer: networkd
  ethernets:
   enp179s0f0: {}
   enp179s0f1: {}

  bonds:
    bond0:
      dhcp4: false
      dhcp6: false
      interfaces:
        - enp179s0f0.324
        - enp179s0f1.324
      parameters:
        mode: active-backup
        primary: enp179s0f0.324
        mii-monitor-interval: 1
      addresses: [insert address here]

  vlans:
    enp179s0f0.324:
      id: 324
      link: enp179s0f0
    enp179s0f1.324:
      id: 324
      link: enp179s0f1
```

If I run `systemctl restart systemd-networkd` after reboot is complete, the vlan interfaces will be successfully added to the bond interface:
> systemd-networkd[2505]: enp179s0f0.324: Enslaving by 'bond0’
systemd-networkd[2505]: bond0: Link 'enp179s0f0.324’ was up when attempting to enslave it. Bringing link down.
systemd-networkd[2505]: enp179s0f0.324: Bringing link down
systemd-networkd[2505]: bond0: Enslaving link 'enp179s0f0.324’
systemd-networkd[2505]: enp179s0f1.324: Enslaving by 'bond0’
systemd-networkd[2505]: bond0: Link 'enp179s0f1.324’ was up when attempting to enslave it. Bringing link down.
systemd-networkd[2505]: enp179s0f1.324: Bringing link down
systemd-networkd[2505]: bond0: Enslaving link 'enp179s0f1.324’
systemd-networkd[2505]: bond0: Configured

My guess is that I’m hitting a race condition that only occurs during boot up:
 - vlan interface created (link status down)
 - networkd creates the bond and attempts to enslave the vlan interface (link is still down)
 - vlan interface link comes up.
 - adding the vlan interface to the bond fails with the error: Could not join netdev: Operation not permitted

Is this a bug, or am I missing something in my Netplan configuration? Or perhaps the bonding of vlan interfaces is not supported?
