### ISSUE TITLE
"systemd-analyze verify" should only verify my file without doing other setup

### ISSUE THREAD

**Issue by gqqnbig** [systemd/systemd#15342]
**Is your feature request related to a problem? Please describe.**

I use the following GitHub Action script. My repository has some systemd unit files, and I want to check syntax of these files. As suggested at #3677 and [the man page](https://github.com/systemd/systemd/blob/master/man/systemd-analyze.xml), `systemd-analyze verify` is the right tool, so I'm using it.

```yaml
name: Systemd units

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: verify units
      run: |
          systemd --version
          sudo systemd-analyze --user
          find deploy -name "*.service" -exec systemd-analyze --user verify '{}' \+
```

The GitHub action fails with error

> Run systemd --version
> systemd 237
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
> Failed to create bus connection: No such file or directory
> ##[error]Process completed with exit code 1.

What's more, I run the same command on my server without `--user` option, I get

> \# find deploy  -name "*.service" -exec systemd-analyze verify '{}' \+
> /lib/systemd/system/dbus.socket:4: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file accordingly.
> snap-lxd-12631.mount: Unit is bound to inactive unit dev-loop3.device. Stopping, too.
> snap-lxd-14194.mount: Unit is bound to inactive unit dev-loop1.device. Stopping, too.
> snap-core-8935.mount: Unit is bound to inactive unit dev-loop2.device. Stopping, too.

[the man page](https://github.com/systemd/systemd/blob/master/man/systemd-analyze.xml) says "Files specified on the command line will be loaded, but also any other units referenced by them." In case the error is because systemd is loading referenced units, I even created a very file unit

```
[Unit]
Description=MyTimer

[Service]
ExecStart=/bin/bash /path/to/mail.sh
```
The dbus and snap still show up.

My guess is that "systemd-analyze verify" does extra job before actually verifying my files.

**Describe the solution you'd like**

I would like `systemd-analyze verify` only verify my files and does minimal extra job. I do not want it to verify dbus and snap, if I'm asking it to verify my file. 

I do not want it to require root permission to verify my file.

I do not want it to "create bus connection" to verify my file.

**Describe alternatives you've considered**
If it's hard, try to make the man page very clear that "systemd-analyze verify" will do some extra job, not only verify the specified files.

**Comment by keszybz** [comment]
> Run systemd --version
> systemd 237

The bug submission template makes it very clear that this tracker is for the last two versions, i.e. >= 244 at this time.

> I do not want it to verify dbus and snap, if I'm asking it to verify my file.

A unit makes only limited sense in isolation. For example, unit dependencies can only be verified by loading other units. So yeah, you get some errors from other units, but systemd doesn't easily know if you are interested in those or not. It *would* be good to add some filtering, but unfortunately the verify code is reusing normal code used to load units in the manager, and simply printing the errors from the load phase. Making this better would require fairly big changes to the code.

> `snap-lxd-12631.mount: Unit is bound to inactive unit dev-loop3.device. Stopping, too.`
> `snap-lxd-14194.mount: Unit is bound to inactive unit dev-loop1.device. Stopping, too.`

Those lines should not be printed. This was fixed a long time, hence my comment about systemd versions.

I'll close this — the thing that you're asking for ("without doing other setup") is already true. Adding better filtering would be a nice enhancement, but I don't think it's likely to happen in the near future.

**Comment by gqqnbig** [comment]
Thanks for the comments. 

I successfully built systemd on GitHub Action runners and verified my service files.. Here is my workflow file

```yaml
name: systemd configuration

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        path: play
    - name: Checkout systemd
      uses: actions/checkout@v1
      with:
        path: systemd
        repository: systemd/systemd
        ref: v245
    - name: Build systemd
      run: |
        cd ${GITHUB_WORKSPACE}/systemd
        sudo apt-get install --yes libc-bin libcap-dev libmount-dev pkg-config gperf python3 ninja-build

        sudo apt-get install --yes python3 python3-pip python3-setuptools python3-wheel ninja-build m4
        sudo -H pip3 install meson
        meson build/ && ninja -C build
    - name: Prepare dependencies
      run: |
        sudo -H pip3 install uwsgi

    - name: Verify service files
      run: |
        cd ${GITHUB_WORKSPACE}/systemd/build
        ./systemd-analyze verify ${GITHUB_WORKSPACE}/play/deploy/systemd/system/uwsgi-play-search.service
```
