### ISSUE TITLE
Dualshock/Sixaxis gyroscope input device is not accessible to the user

### ISSUE THREAD

**Issue by Gigadoc2** [systemd/systemd#17691]
**systemd version the issue has been seen with**
 > systemd 246 (246.6-1-arch)
 > +PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux 5.9.9-arch1-1

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 After connecting a "Sony PLAYSTATION(R)3 Controller" either via USB or Bluetooth; both the input device for the "gamepad parts" (buttons and sticks) and the input device for the motion controls should be accessible to the currently active user session in the same way.

**Unexpected behaviour you saw**
 After connecting the controller, the input device for the "gamepad parts" has ACLs set to allow direct access by the currently logged in user, but the input device for the motion controls does not.

**Steps to reproduce the problem**
Connect a PS3 controller, either via USB or Bluetooth (USB is ostensibly easier as no pairing is involved), and observe the different permissions for the two input devices (here, `event26` are the motion controls and `event27` the rest of the controller):
```
$ LANG=C getfacl /dev/input/event2{6,7}
getfacl: Removing leading '/' from absolute path names
# file: dev/input/event26
# owner: root
# group: input
user::rw-
group::rw-
other::---

# file: dev/input/event27
# owner: root
# group: input
user::rw-
user:gigadoc2:rw-
group::rw-
mask::rw-
other::---
```
Optionally, launch a motion-control aware program (e.g. the Dolphin Emulator), and see how the motion controls are not listed as valid inputs. Add the required ACL to `event26` manually and observe how the program can now make use of the motion controls.

**Potential solution**
Initially I wanted to report this along with a fix in a merge request, but trying to figure out a proper set of rules for this I realized that I do not know what the proper behaviour should be for this sort of input device.

If I understand things correctly, most input devices do _not_ get direct ACLs for the current user, but instead the logind mechanism of claiming devices is used. However, joysticks seem to be an exception to that, as they have an explicit rule to get "user access tagged" here: https://github.com/systemd/systemd/blob/c5b6b4b6d08cf4c16a871401358faeb5a186c02a/src/login/70-uaccess.rules.m4#L71
This seems in line with how joysticks are currently used, they are not handled by the compositor, but by the specialised application directly.
So this particuar controller (and maybe the PS4 ones as well, I don't own one) seems to be an edge case, since the motion controls are (for whatever reason) exposed in a second device, separate from the rest of the gamepad (which is properly tagged and handled as such).

Based on that, I can think of two ways to handle this case:
 1. Match this controller in an explicit rule and tag it as a joystick, so that both input devices are treated like joysticks.
 2. Match the motion control device explicitly and tag it with uaccess.

I don't know whether the first way is correct, as the motion control device would then be of two types at the same time (ID_INPUT_ACCELEROMETER and ID_INPUT_JOYSTICK). The second way avoids this, but is more of a special case (if the handling of joystick devices were to change in the future, the handling of this particular accelerometer would need to be changed as well). Both solutions have the downside that they are explicitly matching this device and are not generalized in any way.

**Comment by yuwata** [comment]
- So, the motion control device can be usable if you adjust the ACL for the device?

- Could you provide the result `udevadm info /dev/input/event26`?

**Comment by Gigadoc2** [comment]
>     * So, the motion control device can be usable if you adjust the ACL for the device?
Yes, after adding read+write rights for my user I can use it (currently the only program I know that can make use of motion controls is the Dolphin Emulator).

>     * Could you provide the result `udevadm info /dev/input/event26`?
This the output when connected over USB:
```
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:054C:0268.0004/input/input29/event26
N: input/event26
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event
S: input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-event-if00
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:054C:0268.0004/input/input29/event26
E: DEVNAME=/dev/input/event26
E: MAJOR=13
E: MINOR=90
E: SUBSYSTEM=input
E: USEC_INITIALIZED=360736210
E: ID_INPUT=1
E: ID_INPUT_ACCELEROMETER=1
E: ID_INPUT_WIDTH_MM=9
E: ID_INPUT_HEIGHT_MM=9
E: ID_VENDOR=Sony
E: ID_VENDOR_ENC=Sony
E: ID_VENDOR_ID=054c
E: ID_MODEL=PLAYSTATION_R_3_Controller
E: ID_MODEL_ENC=PLAYSTATION\x28R\x293\x20Controller
E: ID_MODEL_ID=0268
E: ID_REVISION=0100
E: ID_SERIAL=Sony_PLAYSTATION_R_3_Controller
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
E: LIBINPUT_DEVICE_GROUP=3/54c/268:usb-0000:00:14.0-2
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event /dev/input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-event-if00
```

This is the output when connected via Bluetooth:
```
P: /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/bluetooth/hci0/hci0:71/0005:054C:0268.0005/input/input31/event26
N: input/event26
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/bluetooth/hci0/hci0:71/0005:054C:0268.0005/input/input31/event26
E: DEVNAME=/dev/input/event26
E: MAJOR=13
E: MINOR=90
E: SUBSYSTEM=input
E: USEC_INITIALIZED=986905845
E: ID_INPUT=1
E: ID_INPUT_ACCELEROMETER=1
E: ID_INPUT_WIDTH_MM=9
E: ID_INPUT_HEIGHT_MM=9
E: ID_BUS=bluetooth
E: LIBINPUT_DEVICE_GROUP=5/54c/268:00:1a:7d:da:71:11
```

For comparison, this is `udevadm info` for the gamepad input device (over USB):
```
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:054C:0268.0004/input/input28/event27
N: input/event27
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-joystick
S: input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-event-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:054C:0268.0004/input/input28/event27
E: DEVNAME=/dev/input/event27
E: MAJOR=13
E: MINOR=91
E: SUBSYSTEM=input
E: USEC_INITIALIZED=360736224
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=Sony
E: ID_VENDOR_ENC=Sony
E: ID_VENDOR_ID=054c
E: ID_MODEL=PLAYSTATION_R_3_Controller
E: ID_MODEL_ENC=PLAYSTATION\x28R\x293\x20Controller
E: ID_MODEL_ID=0268
E: ID_REVISION=0100
E: ID_SERIAL=Sony_PLAYSTATION_R_3_Controller
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_0
E: LIBINPUT_DEVICE_GROUP=3/54c/268:usb-0000:00:14.0-2
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-joystick /dev/input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-event-joystick
E: TAGS=:uaccess:seat:
```

**Comment by whot** [comment]
what does `libinput record` (or `evemu-record` at a pinch)` say about this device? Wondering if it's possible to adjust the input-id builtin to cover this case.

**Comment by Gigadoc2** [comment]
USB connection:
```yaml
version: 1
ndevices: 1
libinput:
  version: "1.16.4"
  git: "unknown"
system:
  kernel: "5.9.11-arch2-1"
  dmi: "dmi:bvnAmericanMegatrendsInc.:bvr3802:bd03/15/2018:br5.12:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnMAXIMUSVIIIHERO:rvrRev1.xx:cvnDefaultstring:ct3:cvrDefaultstring:"
devices:
- node: /dev/input/event26
  evdev:
    # Name: Sony PLAYSTATION(R)3 Controller Motion Sensors
    # ID: bus 0x3 vendor 0x54c product 0x268 version 0x8111
    # Size in mm: 9x9
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value           0
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    #   Event code 1 (ABS_Y)
    #       Value         113
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    #   Event code 2 (ABS_Z)
    #       Value          23
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    # Properties:
    #    Property 6 (INPUT_PROP_ACCELEROMETER)
    name: "Sony PLAYSTATION(R)3 Controller Motion Sensors"
    id: [3, 1356, 616, 33041]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      3: [0, 1, 2] # EV_ABS
    absinfo:
      0: [-512, 511, 4, 0, 113]
      1: [-512, 511, 4, 0, 113]
      2: [-512, 511, 4, 0, 113]
    properties: [6]
  hid: [5, 1, 9, 4, 161, 1, 161, 2, 133, 1, 117, 8, 149, 1, 21, 0, 38, 255, 0, 129, 3, 117, 1, 149, 19, 21, 0, 37, 1, 53, 0, 69, 1, 5, 9, 25, 1, 41, 19, 129, 2, 117, 1, 149, 13, 6, 0, 255, 129, 3, 21, 0, 38, 255, 0, 5, 1, 9, 1, 161, 0, 117, 8, 149, 4, 53, 0, 70, 255, 0, 9, 48, 9, 49, 9, 50, 9, 53, 129, 2, 192, 5, 1, 117, 8, 149, 39, 9, 1, 129, 2, 117, 8, 149, 48, 9, 1, 145, 2, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 2, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 238, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 239, 117, 8, 149, 48, 9, 1, 177, 2, 192, 192 ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_ACCELEROMETER=1
    - ID_INPUT_HEIGHT_MM=9
    - ID_INPUT_WIDTH_MM=9
    - LIBINPUT_DEVICE_GROUP=3/54c/268:usb-0000:00:14.0-2
  quirks:
  events:
  - evdev:
    - [  0,      0,   3,   2,      22] # EV_ABS / ABS_Z                    22 (-1)
  - evdev:
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0,  10001,   3,   2,      21] # EV_ABS / ABS_Z                    21 (-1)
    - [  0,  10001,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +10ms
```

Bluetooth:
```yaml
version: 1
ndevices: 1
libinput:
  version: "1.16.4"
  git: "unknown"
system:
  kernel: "5.9.11-arch2-1"
  dmi: "dmi:bvnAmericanMegatrendsInc.:bvr3802:bd03/15/2018:br5.12:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnMAXIMUSVIIIHERO:rvrRev1.xx:cvnDefaultstring:ct3:cvrDefaultstring:"
devices:
- node: /dev/input/event26
  evdev:
    # Name: Sony PLAYSTATION(R)3 Controller Motion Sensors
    # ID: bus 0x5 vendor 0x54c product 0x268 version 0x8000
    # Size in mm: 9x9
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value           0
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    #   Event code 1 (ABS_Y)
    #       Value         112
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    #   Event code 2 (ABS_Z)
    #       Value          22
    #       Min          -512
    #       Max           511
    #       Fuzz            4
    #       Flat            0
    #       Resolution    113
    # Properties:
    #    Property 6 (INPUT_PROP_ACCELEROMETER)
    name: "Sony PLAYSTATION(R)3 Controller Motion Sensors"
    id: [5, 1356, 616, 32768]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      3: [0, 1, 2] # EV_ABS
    absinfo:
      0: [-512, 511, 4, 0, 113]
      1: [-512, 511, 4, 0, 113]
      2: [-512, 511, 4, 0, 113]
    properties: [6]
  hid: [5, 1, 9, 4, 161, 1, 161, 2, 133, 1, 117, 8, 149, 1, 21, 0, 38, 255, 0, 129, 3, 117, 1, 149, 19, 21, 0, 37, 1, 53, 0, 69, 1, 5, 9, 25, 1, 41, 19, 129, 2, 117, 1, 149, 13, 6, 0, 255, 129, 3, 21, 0, 38, 255, 0, 5, 1, 9, 1, 161, 0, 117, 8, 149, 4, 53, 0, 70, 255, 0, 9, 48, 9, 49, 9, 50, 9, 53, 129, 2, 192, 5, 1, 117, 8, 149, 39, 9, 1, 129, 2, 117, 8, 149, 48, 9, 1, 145, 2, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 2, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 238, 117, 8, 149, 48, 9, 1, 177, 2, 192, 161, 2, 133, 239, 117, 8, 149, 48, 9, 1, 177, 2, 192, 192, 0 ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_ACCELEROMETER=1
    - ID_INPUT_HEIGHT_MM=9
    - ID_INPUT_WIDTH_MM=9
    - LIBINPUT_DEVICE_GROUP=5/54c/268:00:1a:7d:da:71:11
  quirks:
  events:
  - evdev:
    - [  0,      0,   3,   2,      21] # EV_ABS / ABS_Z                    21 (-1)
  - evdev:
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0,   8750,   3,   0,       8] # EV_ABS / ABS_X                     8 (+8)
    - [  0,   8750,   3,   2,      12] # EV_ABS / ABS_Z                    12 (-9)
    - [  0,   8750,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +8ms
```

I have shortened the events list, as I assume they are not relevant here (and the motion controls generate a lot of events).
