### ISSUE TITLE
networkd: no SLAAC on 802.3ad bonded interface until reconfigure

### ISSUE THREAD

**Issue by mas90** [systemd/systemd#19627]
**systemd version the issue has been seen with**
 > 247.3 (and 245.4)

**Used distribution**
 > Ubuntu

**Linux kernel version used** (`uname -a`)
 > `5.8.0-53-generic`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > My configuration uses an 802.3ad bond, using DHCP for IPv4 and SLAAC for IPv6.  No IPv6 address is autoconfigured vla SLAAC and router advertisement packets are entirely ignored.  `networkctl reconfigure bond0` after the interface has been configured causes SLAAC to start working.

**Steps to reproduce the problem**
1. Configure LACP (802.3ad) on the connected switch port(s); connect to a network with DHCPv4 and SLAAC
2. Configure networkd as follows:

bond0.network:
```
[Match]
Name=bond0

[Network]
DHCP=yes
LinkLocalAddressing=ipv6
ConfigureWithoutCarrier=yes

[DHCP]
RouteMetric=100
UseMTU=true
```

bond0.netdev:
```
[NetDev]
Name=bond0
Kind=bond

[Bond]
Mode=802.3ad
```

bondports.netdev (for a trivial configuration on one NIC):
```
[Match]
Name=eno1

[Network]
LinkLocalAddressing=no
Bond=bond0
```

In my case this is actually autogenerated via netplan with the following configuration:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    bondports:
      match: {name: "eno1"}
  bonds:
    bond0:
      parameters:
        mode: 802.3ad
      interfaces: [bondports]
      dhcp4: yes
      dhcp6: yes
```
3. Reboot (or *fully delete* any existing bond0 device etc. and apply the configuration: e.g. `echo -bond0 > /sys/class/net/bonding_master ; netplan apply`)
4. Observe that bond0 has no SLAAC IPv6 address (besides the link-local one), but does have an IPv4 address via DHCP
5. Wait for RA packets to arrive from the router; observe that they too don't cause an autoconfigured address to appear, nor any IPv6 routes
6. `networkctl reconfigure bond0`, or `netplan apply` again
7. Observe that bond0 now has an IPv6 address
