### ISSUE TITLE
networkd mangles mac address specified by system administrator

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#21649]
**systemd version the issue has been seen with**
> master

**Used distribution**
 > own project

**Linux kernel version used** (`uname -a`)

 > `Linux asusb450eg 5.15.6-k5 #2 SMP Mon Dec 6 18:19:54 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > If a mac address is specified by the system administrator mac address should be applied to the interface without mangling it.

**Unexpected behaviour you saw**
 >Dec 07 00:32:23 asusb450eg systemd-networkd[262]: br0: Specified MAC address does not have the local assignment bit set, setting the bit.
Dec 07 00:32:23 asusb450eg systemd-networkd[262]: br0: netdev ready
```
ip addr sh dev br0
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 06:d9:f5:f8:4d:58 brd ff:ff:ff:ff:ff:ff
```

```
cat /etc/netplan/01-default.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      snipped for brevity
  bridges:
    br0:
      dhcp4: true
      dhcp-identifier: mac
      dhcp6: true
      accept-ra: true
      macaddress: 04:d9:f5:f8:4d:58
      interfaces:
        - enp3s0
      parameters:
        stp: false
        forward-delay: 0
```

```
 cat /run/systemd/network/10-netplan-br0.netdev
[NetDev]
Name=br0
MACAddress=04:d9:f5:f8:4d:58
Kind=bridge

[Bridge]
ForwardDelaySec=0
STP=false
```

```
cat /run/systemd/network/10-netplan-br0.network
[Match]
Name=br0

[Link]
MACAddress=04:d9:f5:f8:4d:58

[Network]
DHCP=yes
LinkLocalAddressing=ipv6
IPv6AcceptRA=yes
ConfigureWithoutCarrier=yes

[DHCP]
ClientIdentifier=mac
RouteMetric=100
UseMTU=true
```

> As you can see networkd set a different mac address and not what I have specifically set causing this box to receive a wring ip address from my router.

**Steps to reproduce the problem**
 > boot a system with a configured bridge which has macaddress set.

Caused by #21517 
Rationale:
While validating a mac address specified in the relevant config files is a must mangling and changing a perfectly valid mac address is a no no.
This could potentially break people's network setups with eg dhcp server bindings.
While having local bit set is technically correct changing something that was set by the system administrator is a no go.
Potential solution:
Issue a  warning about local bit not being set, but do not mangle the mac.

cc @yuwata
