### ISSUE TITLE
Ideapad Flex 5: Unknown key pressed. hwdb/udev issue? 

### ISSUE THREAD

**Issue by krutoileshii** [systemd/systemd#21856]
**systemd version the issue has been seen with**
 > `systemd 249 (249.7-2-arch)`

**Used distribution**
 > `Arch Linux x86_64 `

**Linux kernel version used** (`uname -a`)
 > `Linux laptop-arch 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > `x86_64 11th Gen Intel i5-1135G7 (8) @ 4.200GHz`
**Extra Info**
OS: Arch Linux x86_64 
Host: 82HS IdeaPad Flex 5 14ITL05 
Kernel: 5.15.10-arch1-1 
Shell: bash 5.1.12 
Resolution: 1920x1080 
DE: GNOME 41.2 
WM: Mutter 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 3187MiB / 15552MiB 

**Expected behaviour you didn't see**
Expecting to see proper key being emitted when laptop is returned back to normal mode from tablet mode.

Not sure what the 22/23 keys should be mapped to. KEY_23 disables touchpad and keyboard, KEY_22 re-enables it. Missing key does nothing yet. Likely hwdb issue.  

If this is a wrong place to report, please let me know where i should file this. Thank you very much for any help/assistance.

**Unexpected behaviour you saw**
Instead, the laptop returns unknown key pressed (see below).

`[271858.592158] atkbd serio0: Unknown key pressed (translated set 2, code 0xf6 on isa0060/serio0).`
`[271858.592167] atkbd serio0: Use 'setkeycodes e076 <keycode>' to make it known. `

**Steps to reproduce the problem**

1. Fold laptop: 
2. Unfold Laptop

**Additional program output to the terminal or log subsystem illustrating the issue**

**libinput events emitted when the screen is folder/unfolded**
EV_KEY / KEY_F22  = 180°
EV_KEY/ KEY_F23 = 360°

The missing key above corresponds to 90°

```
[yevsey@laptop-arch ~]$ libinput record
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event2:	AT Translated Set 2 keyboard
/dev/input/event3:	Ideapad extra buttons
/dev/input/event4:	MSFT0001:00 04F3:3140 Mouse
/dev/input/event5:	MSFT0001:00 04F3:3140 Touchpad
/dev/input/event6:	PC Speaker
/dev/input/event7:	Integrated Camera: Integrated C
/dev/input/event8:	Wacom HID 5218 Pen
/dev/input/event9:	Wacom HID 5218 Finger
/dev/input/event10:	Video Bus
/dev/input/event11:	sof-hda-dsp Mic
/dev/input/event12:	sof-hda-dsp Headphone
/dev/input/event13:	sof-hda-dsp HDMI/DP,pcm=3
/dev/input/event14:	sof-hda-dsp HDMI/DP,pcm=4
/dev/input/event15:	sof-hda-dsp HDMI/DP,pcm=5
Select the device event number: 3
Recording to 'stdout'.
# libinput record
version: 1
ndevices: 1
libinput:
  version: "1.19.3"
  git: "unknown"
system:
kernel: "5.15.10-arch1-1"
dmi: "dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:"
devices:
- node: /dev/input/event3
  evdev:
    # Name: Ideapad extra buttons
    # ID: bus 0x19 vendor 00 product 00 version 00
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 1 (KEY_ESC)
    #   Event code 148 (KEY_PROG1)
    #   Event code 149 (KEY_PROG2)
    #   Event code 186 (KEY_F16)
    #   Event code 190 (KEY_F20)
    #   Event code 192 (KEY_F22)
    #   Event code 193 (KEY_F23)
    #   Event code 202 (KEY_PROG3)
    #   Event code 203 (KEY_PROG4)
    #   Event code 212 (KEY_CAMERA)
    #   Event code 227 (KEY_SWITCHVIDEOMODE)
    #   Event code 240 (KEY_UNKNOWN)
    #   Event code 247 (KEY_RFKILL)
    # Event type 4 (EV_MSC)
    #   Event code 4 (MSC_SCAN)
    # Properties:
    name: "Ideapad extra buttons"
    id: [25, 0, 0, 0]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [1, 148, 149, 186, 190, 192, 193, 202, 203, 212, 227, 240, 247] # EV_KEY
      4: [4] # EV_MSC
    properties: []
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_KEY=1
    - LIBINPUT_DEVICE_GROUP=19/0/0:ideapad
  quirks:
  events:
  # Current time is 19:31:01
  # Current time is 19:31:07
  - evdev:
    - [  0,      0,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  0,      0,   1, 193,       1] # EV_KEY / KEY_F23                   1
    - [  0,      0,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  - evdev:
    - [  0,     18,   1, 193,       0] # EV_KEY / KEY_F23                   0
    - [  0,     18,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  # Current time is 19:31:10
  # Current time is 19:31:16
  - evdev:
    - [  8, 943244,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [  8, 943244,   1, 192,       1] # EV_KEY / KEY_F22                   1
    - [  8, 943244,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +8943ms
  - evdev:
    - [  8, 943258,   1, 192,       0] # EV_KEY / KEY_F22                   0
    - [  8, 943258,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  # Current time is 19:31:20
  # Current time is 19:31:31
  - evdev:
    - [ 23, 649655,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 23, 649655,   1, 193,       1] # EV_KEY / KEY_F23                   1
    - [ 23, 649655,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +14706ms
  - evdev:
    - [ 23, 649681,   1, 193,       0] # EV_KEY / KEY_F23                   0
    - [ 23, 649681,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  # Current time is 19:31:35
  - evdev:
    - [ 33, 247089,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 33, 247089,   1, 192,       1] # EV_KEY / KEY_F22                   1
    - [ 33, 247089,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +9598ms
  - evdev:
    - [ 33, 247111,   1, 192,       0] # EV_KEY / KEY_F22                   0
    - [ 33, 247111,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +0ms
  # Current time is 19:31:40
```
**modalias**

```
[yevsey@laptop-arch ~]$ cat /sys/class/dmi/id/modalias
dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:
```

**udevadm test /sys/class/input/event3**
```
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
Trying to open "/usr/lib/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          249
file size:        11559359 bytes
header size             80 bytes
strings            2377271 bytes
nodes              9182008 bytes
Load module index
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Loaded timestamp for '/etc/systemd/network'.
Loaded timestamp for '/usr/lib/systemd/network'.
Parsed configuration file /usr/lib/systemd/network/99-default.link
Parsed configuration file /usr/lib/systemd/network/80-iwd.link
Created link configuration context.
Loaded timestamp for '/etc/udev/rules.d'.
Loaded timestamp for '/usr/lib/udev/rules.d'.
...
event3: /usr/lib/udev/rules.d/50-udev-default.rules:29 GROUP 994
event3: /usr/lib/udev/rules.d/60-evdev.rules:8 Importing properties from results of builtin command 'hwdb --subsystem=input --lookup-prefix=evdev:'
event3: hwdb modalias key: "input:b0019v0000p0000e0000-e0,1,4,k94,95,BA,BE,C0,C1,CA,CB,D4,E3,F0,F7,ram4,lsfw"
event3: No entry found from hwdb.
event3: /usr/lib/udev/rules.d/60-evdev.rules:8 Failed to run builtin 'hwdb --subsystem=input --lookup-prefix=evdev:': No data available
value '[dmi/id]modalias' is 'dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:'
event3: /usr/lib/udev/rules.d/60-evdev.rules:18 Importing properties from results of builtin command 'hwdb 'evdev:name:Ideapad extra buttons:phys:ideapad/input0:ev:13:dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:''
event3: No entry found from hwdb.
event3: /usr/lib/udev/rules.d/60-evdev.rules:18 Failed to run builtin 'hwdb 'evdev:name:Ideapad extra buttons:phys:ideapad/input0:ev:13:dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:'': No data available
value '[dmi/id]modalias' is 'dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:'
event3: /usr/lib/udev/rules.d/60-evdev.rules:23 Importing properties from results of builtin command 'hwdb 'evdev:name:Ideapad extra buttons:dmi:bvnLENOVO:bvrFXCN15WW:bd09/30/2020:br1.15:efr1.12:svnLENOVO:pn82HS:pvrIdeaPadFlex514ITL05:rvnLENOVO:rnLNVNB161216:rvrSDK0J40700WIN:cvnLENOVO:ct31:cvrIdeaPadFlex514ITL05:skuLENOVO_MT_82HS_BU_idea_FM_IdeaPadFlex514ITL05:''
event3: /usr/lib/udev/rules.d/60-evdev.rules:23 Importing properties from results of builtin command 'keyboard'
event3: keyboard: mapping scan code 8 (0x8) to key code 190 (0xbe)
event3: keyboard: mapping scan code 13 (0xd) to key code 247 (0xf7)
event3: keyboard: mapping scan code 66 (0x42) to key code 193 (0xc1)
event3: keyboard: mapping scan code 67 (0x43) to key code 192 (0xc0)
event3: /usr/lib/udev/rules.d/60-input-id.rules:5 Importing properties from results of builtin command 'input_id'
input3: capabilities/ev raw kernel attribute: 13
input3: capabilities/abs raw kernel attribute: 0
input3: capabilities/rel raw kernel attribute: 0
input3: capabilities/key raw kernel attribute: 81000800100c03 4400000000300000 0 2
input3: properties raw kernel attribute: 0
event3: test_key: checking bit block 0 for any keys; found=1
event3: test_key: checking bit block 64 for any keys; found=1
event3: test_key: checking bit block 128 for any keys; found=1
event3: test_key: checking bit block 192 for any keys; found=1
event3: /usr/lib/udev/rules.d/60-input-id.rules:6 Importing properties from results of builtin command 'hwdb --subsystem=input --lookup-prefix=id-input:modalias:'
event3: hwdb modalias key: "input:b0019v0000p0000e0000-e0,1,4,k94,95,BA,BE,C0,C1,CA,CB,D4,E3,F0,F7,ram4,lsfw"
event3: No entry found from hwdb.
event3: /usr/lib/udev/rules.d/60-input-id.rules:6 Failed to run builtin 'hwdb --subsystem=input --lookup-prefix=id-input:modalias:': No data available
event3: /usr/lib/udev/rules.d/60-persistent-input.rules:35 Importing properties from results of builtin command 'path_id'
event3: /usr/lib/udev/rules.d/60-persistent-input.rules:40 LINK 'input/by-path/pci-0000:00:1f.0-platform-VPC2004:00-event'
event3: /usr/lib/udev/rules.d/65-libwacom.rules:19 Importing properties from results of builtin command 'hwdb --subsystem=input '--lookup-prefix=libwacom:name:Ideapad extra buttons:''
event3: hwdb modalias key: "input:b0019v0000p0000e0000-e0,1,4,k94,95,BA,BE,C0,C1,CA,CB,D4,E3,F0,F7,ram4,lsfw"
event3: No entry found from hwdb.
event3: /usr/lib/udev/rules.d/65-libwacom.rules:19 Failed to run builtin 'hwdb --subsystem=input '--lookup-prefix=libwacom:name:Ideapad extra buttons:'': No data available
event3: /usr/lib/udev/rules.d/80-libinput-device-groups.rules:4 Importing properties from results of 'libinput-device-group /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3'
event3: Starting 'libinput-device-group /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3'
Successfully forked off '(spawn)' as PID 28143.
event3: 'libinput-device-group /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3'(out) 'LIBINPUT_DEVICE_GROUP=19/0/0:ideapad'
event3: Process 'libinput-device-group /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3' succeeded.
event3: Handling device node '/dev/input/event3', devnum=c13:67
event3: Preserve permissions of /dev/input/event3, uid=0, gid=994, mode=0660
event3: Found 'c13:67' claiming '/run/udev/links/input\x2fby-path\x2fpci-0000:00:1f.0-platform-VPC2004:00-event'
event3: Preserve already existing symlink '/dev/input/by-path/pci-0000:00:1f.0-platform-VPC2004:00-event' to '../event3'
event3: Preserve already existing symlink '/dev/char/13:67' to '../input/event3'
event3: sd-device: Created db file '/run/udev/data/c13:67' for '/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3'
event3: Handling device node '/dev/input/event3', devnum=c13:67
event3: Preserve permissions of /dev/input/event3, uid=0, gid=994, mode=0660
event3: Found 'c13:67' claiming '/run/udev/links/input\x2fby-path\x2fpci-0000:00:1f.0-platform-VPC2004:00-event'
event3: Preserve already existing symlink '/dev/input/by-path/pci-0000:00:1f.0-platform-VPC2004:00-event' to '../event3'
event3: Preserve already existing symlink '/dev/char/13:67' to '../input/event3'
DEVPATH=/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input3/event3
DEVNAME=/dev/input/event3
MAJOR=13
MINOR=67
ACTION=add
SUBSYSTEM=input
TAGS=:power-switch:
KEYBOARD_KEY_08=f20
KEYBOARD_KEY_0d=rfkill
KEYBOARD_KEY_42=f23
KEYBOARD_KEY_43=f22
ID_INPUT=1
ID_INPUT_KEY=1
ID_PATH=pci-0000:00:1f.0-platform-VPC2004:00
ID_PATH_TAG=pci-0000_00_1f_0-platform-VPC2004_00
DEVLINKS=/dev/input/by-path/pci-0000:00:1f.0-platform-VPC2004:00-event
CURRENT_TAGS=:power-switch:
LIBINPUT_DEVICE_GROUP=19/0/0:ideapad
USEC_INITIALIZED=16889052
Unload module index
Unloaded link configuration context.
```
