### ISSUE TITLE
Hotkeys not working in MSI GF63 11UC

### ISSUE THREAD

**Issue by soumyaDghosh** [systemd/systemd#26201]
### systemd version the issue has been seen with

systemd 251 (251.4-1ubuntu7)

### Used distribution

Ubuntu 22.10

### Linux kernel version used

5.19.0-29-generic

### CPU architectures issue was seen on

x86_64

### Component

hardware database files

### Expected behaviour you didn't see

Fn+F3 = Disable Touchpad
Fn+F10= Enable/Disable Airplane mode

### Unexpected behaviour you saw

Pressing the above keys does nothing

### Additional program output to the terminal or log subsystem illustrating the issue

**Pressing Fn+F3**
````
- evdev:
    - [ 20, 294833,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 294833,   1,  29,       1] # EV_KEY / KEY_LEFTCTRL              1
    - [ 20, 294833,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +16170ms
  - evdev:
    - [ 20, 295921,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 295921,   1, 125,       1] # EV_KEY / KEY_LEFTMETA              1
    - [ 20, 295921,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +1ms
  - evdev:
    - [ 20, 306350,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 306350,   1,  85,       1] # EV_KEY / KEY_ZENKAKUHANKAKU        1
    - [ 20, 306350,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +11ms
  - evdev:
    - [ 20, 316232,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 316232,   1,  29,       0] # EV_KEY / KEY_LEFTCTRL              0
    - [ 20, 316232,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +10ms
  - evdev:
    - [ 20, 337595,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 337595,   1, 125,       0] # EV_KEY / KEY_LEFTMETA              0
    - [ 20, 337595,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +21ms
  - evdev:
    - [ 20, 346754,   4,   4,      30] # EV_MSC / MSC_SCAN                 30 (obfuscated)
    - [ 20, 346754,   1,  85,       0] # EV_KEY / KEY_ZENKAKUHANKAKU        0
    - [ 20, 346754,   0,   0,       0] # ------------ SYN_REPORT (0) ---------- +9ms
  # Current time is 22:04:55`


``````
The airplane mode doesn't record
