### ISSUE TITLE
systemd-networkd-wait-online is failing with a bridge interface.  Boot pauses for two minutes.

### ISSUE THREAD

**Issue by elyograg** [systemd/systemd#27724]
### systemd version the issue has been seen with

systemd-networkd-wait-online

### Used distribution

Ubuntu 22.04 server

### Linux kernel version used

6.1.0-1012-oem

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd-wait-online

### Unexpected behaviour you saw

Boot pauses for two minutes waiting for the network.  Running the program manually shows a timeout error, and takes two minutes to time out.

![image](https://github.com/systemd/systemd/assets/4984827/2eaf3899-becc-4d6f-ac2d-dbac5c6f3256)

The network is configured by netplan, not systemd and not /etc/network/interfaces.

### Steps to reproduce the problem

Configure the network with a bridge interface in netplan. Reboot.

### Additional program output to the terminal or log subsystem illustrating the issue

```yaml
# Netplan config:

network:
  #debug: true
  version: 2
  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false
      optional: true
    eno2:
      dhcp4: false
      dhcp6: false
      optional: true
    eno3:
      dhcp4: false
      dhcp6: false
      optional: true
    eno4:
      dhcp4: false
      dhcp6: false
      optional: true
    enp5s0:
      dhcp4: false
      dhcp6: false
      optional: true
  bridges:
    br0:
      dhcp4: false
      dhcp6: false
      interfaces: [eno1, eno2]
      addresses: [192.168.217.202/24]
      routes:
      - to: default
        via: 192.168.217.1
      - to: 192.168.57.0/24
        via: 192.168.217.10
      nameservers:
        addresses: [192.168.217.202,192.168.217.200]
        search: [int.elyograg.org,elyograg.org]
      parameters:
        stp: false
        forward-delay: 5

```
