### ISSUE TITLE
sysusers: /etc/passwd lock fails on WSL1

### ISSUE THREAD

**Issue by maxprehl** [systemd/systemd#29512]
### systemd version the issue has been seen with

254.5-1

### Used distribution

Debian Sid

### Linux kernel version used

4.4.0-19041-Microsoft (WSL1)

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysusers

### Expected behaviour you didn't see

During dpkg postinstall scripts, systemd-sysusers SHOULD take a /etc/passwd lock and then make updates based on conf files. 

I specifically encountered issues during dpkg postinstall scripts for:
- cron-daemon-common - cron-daemon-common:amd64 (3.0pl1-165, 3.0pl1-175)
- systemd - systemd:amd64 (254.1-2, 254.5-1)
- systemd-timesyncd - stemd-timesyncd:amd64 (254.1-2, 254.5-1)
- udev - udev:amd64 (254.1-2, 254.5-1),

As far as i can tell, this is a Wont-Fix from Microsoft on implementing the `fcntl(F_SETLK)` fixes in WSL1. https://github.com/Microsoft/WSL/issues/1927

I figured I'd bring the issue to your attention anyway since it is breaking updates to these systems.  Some kind of fallback would be really nice.  But, if WSL1 is not a target for you guys, feel free to disregard.  If you do close this issue, any feedback or advice on where to go from here would be much appreciated.  Thanks.

### Unexpected behaviour you saw

dpkg fails:

```yaml
Setting up systemd (254.5-1) ...
Failed to take /etc/passwd lock: Invalid argument
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Running systemd-sysusers manually results in the same error:

```console
$ systemd-sysusers /usr/lib/sysusers.d/cron-daemon-common.conf
Failed to take /etc/passwd lock: Permission denied
```

### Steps to reproduce the problem

1. Be using WSL1.  
2. Attempt to use systemd-sysusers.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Taken from: https://superuser.com/a/1805742/1298503

systemd.postinsts script calls systemd-sysusers, and it in turn tries to get a lock with fcntl F_OFD_SETLKW which fails.

strace output of sudo systemd-sysusers:

openat(AT_FDCWD, "/etc/.pwd.lock", O_WRONLY|O_CREAT|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC, 0600) = 3
fcntl(3, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = -1 EINVAL (Invalid argument)
```
