### ISSUE TITLE
systemd-networkd-wait-online fails when you disable IPv6 stack in /etc/default/ufw ( IPV6=no )

### ISSUE THREAD

**Issue by D33M0N** [systemd/systemd#31049]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04 LTS

### Linux kernel version used

5.15.0-91-generic

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

systemd-networkd-wait-online.service does not time out and does not fail.

### Unexpected behaviour you saw

systemd-networkd-wait-online.service times out and fails.

### Steps to reproduce the problem

1. sudo sed -i 's/IPV6=yes/IPV6=no/g' /etc/default/ufw
2. reboot
3. observe system bootup time being extended about 2 minutes and `systemd-networkd-wait-online.service` timeout and fail.

### WORKAROUND (can't really call it "fix")

The current working workaround was to add `link-local: [ ]` to every interface in /etc/netplan/*.yaml .
like:
```
  ethernets:
    ens160:
      link-local: [ ]
      dhcp4: no
      dhcp6: no
      addresses:
      - 172.16.100.100
```
