### ISSUE TITLE
Wrong PCR 11 value with ukify and systemd-stub

### ISSUE THREAD

**Issue by jsommr** [systemd/systemd#35820]
### systemd version the issue has been seen with

systemd-boot-efi 257~rc2-3

### Used distribution

Debian 13 (Trixie)

### Linux kernel version used

6.10.10-surface-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-stub

### Expected behaviour you didn't see

The measured PCR 11 values

### Unexpected behaviour you saw

PCR 11 does have a value (non-zero), but it's not any of those measured by systemd-measure.

### Steps to reproduce the problem

Boot sequence is UEFI -> Shim -> Stub

This is my config:
```
[UKI]
Cmdline=@/etc/kernel/cmdline
SecureBootPrivateKey=/etc/ssl/private/os.pem
SecureBootCertificate=/etc/ssl/certs/os.pem
PCRBanks=sha1
SBAT=@/etc/kernel/sbat.csv
Stub=/usr/lib/systemd/boot/efi/linuxx64.efi.stub

[PCRSignature:initrd]
PCRPrivateKey=/etc/systemd/tpm2-pcr-private-key-initrd.pem
PCRPublicKey=/etc/systemd/tpm2-pcr-public-key-initrd.pem
```
And my initramfs post-update hook:
```bash
ukify build --config /etc/kernel/uki.conf --linux /boot/vmlinuz-$1 --initrd /boot/initrd.img-$1 --output /boot/efi/grubx64.efi --uname $1 --measure
```
When printing the PCR values (tpm2_pcrread) in initrd using a script in /etc/initramfs-tools/scripts/init-bottom/... the value of PCR SHA1(11) does not match any of the measured values.

Running `systemd-pcrextend --graceful enter-initrd` before tpm2_pcrread prints: `Kernel stub did not measure kernel image into PCR 11, skipping userspace measurement, too.`. Setting `SYSTEMD_FORCE_MEASURE=1` forces a measurement, but the result is also not what was systemd-measure'd.

I don't understand how PCR 11 can have a non-zero value if the stub didn't extend it.

Don't know if it's of any use, but I can verify the policies and signatures in /.extra/tpm2-pcr-signature.json with `tpm2_verifysignature -c signing_key.ctx -g sha1 -m pcr.policy -s pcr.signature -t verification.tkt -f rsassa` where pcr.policy and pcr.signature are decoded from JSON. It doesn't work when I use verification.tkt in a session policy because of the PCR issue.

Removing quiet from cmdline reveals "Measured initrd data into PCR 9". This seems to be output from the kernel efi stub.

The efivars are set:
```
ls /sys/firmware/efi/efivars/ | grep "4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"
LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
LoaderFirmwareInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
LoaderFirmwareType-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
LoaderImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubFeatures-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubImageIdentifier-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubInfo-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubPcrKernelImage-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
StubProfile-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
```

### Additional program output to the terminal or log subsystem illustrating the issue

```
ukify inspect /boot/efi/grubx64.efi 
.sbat:
  size: 325 bytes
  sha256: c5935da2a7a5548cb809c9f34907dee341abe6aa634e79db53b3195083fd4cb2
  text:
    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    systemd-stub,1,The systemd Developers,systemd,257,https://systemd.io/
    systemd-stub.debian,1,Debian GNU/Linux,systemd,257~rc2-3,https://tracker.debian.org/pkg/systemd
    uki,1,UKI,uki,1,https://uapi-group.org/specifications/specs/unified_kernel_image/
    
.osrel:
  size: 222 bytes
  sha256: d233f3430906f91316821d805531cf09fd0d5dad628a89a40e56bc65301c0ca7
  text:
    PRETTY_NAME="Debian GNU/Linux trixie/sid"
    NAME="Debian GNU/Linux"
    VERSION_CODENAME=trixie
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
.cmdline:
  size: 143 bytes
  sha256: c699197860ed93b646e3354ba6261d4e87c1c48a2914b1bfbae0abd8caca06e4
  text:
    root=UUID=9827c96c-8942-4e12-96cc-a655ab71549d quiet rw nosgx systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on
.uname:
  size: 17 bytes
  sha256: 9dbe4d33f8b506ddc45878a7d2dd09b693dd39d84a9ca3f7a30db30faf9184db
  text:
    6.10.10-surface-1
.pcrpkey:
  size: 451 bytes
  sha256: 248da07dc04250d15bf480628de5c71a08ae74fb4aa32a66f5b9df289930ad08
  text:
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtlCt9Ki5wUu4cF6Irk5h
    4Y1P8xrUzFB3DcshCSC/SGPOtm+KA6OLq6M3rwGAajEkj7/iU8/v+og+ufinHBK0
    G6wWxju1N2jm+4EYUJinJgvicRE5XAMPaFtvtBkJMpFSap3g636lpU+eb4Ez7oa6
    i+DfXgUB0IAy9f02paw1J+jNasRtQRfzYydjfn5iu9smT5wqwwQ8x2OvTyhWUUei
    0SDz4NGKd8TIj7WETHV+/ChQssiPlM2g0zr6WWeRyf8GmMVgMwc1F9jr+Q2UP5Vm
    E92a9YoOpw0Po2VmC7sB4eD1tJQ1E+KTT5gKWEswo4ObsiBy39Ae2V2jsS0s+tST
    nwIDAQAB
    -----END PUBLIC KEY-----
.initrd:
  size: 27924351 bytes
  sha256: 3831603a109e81db957da00f25a0d3ee77566f0a28c04adcba11fbecac701571
.pcrsig:
  size: 2098 bytes
  sha256: dd2be74289e24b860e85197a3efff17cde0e8df2c7ee50821bf886a5adac8538
  text:
    {"sha1": [{"pcrs": [11], "pkfp": "8761d8f359619a94dec162326edbc985091f015f004f6a177fa828681fc23387", "pol": "b5e889b1aa0fbaa15550c4aadbbe8f07d3e4945ec4cdb37bc1558faa6d743f37", "sig": "Od6eDr71M2PPYS1wcwh++sMfjtOQc+nEN9LjxgaAvBuD++PwiOY9TMztgQatc3q3gyjBdY0pzkohkMGeSgennHygD1KBG2x7zn61bR3oeVRit4jo+xHt91Wuzkj1VkL0d/g67vlkiAL9zLhtbITQp58pZ3PxYRs3/Kvfbmzhv14C4GGXDb6SFFof5yYU0gwXuXMyymk9mtb/WQX3xHYe2v2OKsj9B82/m+KCjHJh+fH057uaSH6Oefa4w4Qpn+1lJ4J4RlOwXKwYUu7Z2kH162Sa6ToCDSylc17LxJK5w8zar2cP1w8PzGV59eVpRpVHWnG43wYScTPWMNQl/s3XIA=="}, {"pcrs": [11], "pkfp": "8761d8f359619a94dec162326edbc985091f015f004f6a177fa828681fc23387", "pol": "91a885d027ae923f9e17adcbd8a5da259dd427956bb53a4c955a931ed1544928", "sig": "LV9+z/zeu9huVifSAwRMEjJ6EQy2herB4AhuOGrviDqGZLE6KmUbfjeBWpXw9+l3XVYvEBjZCyzOJAZn8Ag5W4SWqj4EpiTWM05+wqEQIMrFpTGOhoE5BpwGGHJUeGZqH9vZqWsRFfrpa0tdGpEyq5xKGqp9m9vg7ZjTn/6xEFEg4S9IWPMapf6nuK2EKtV13kd5o7Cnlw7nVPSC/Gti4Gfjhd6LMVSR/6KE4V+d29m4a0DVueUBg77bzX7sauPTue7ThOzcL30TPTVgy7klYy6KDnL12JiJzZ7Vd8Lv91BMBC3R6dYWvrP/UA/hikvGb3LKgLpcuNlZRSkUZYBAPg=="}, {"pcrs": [11], "pkfp": "8761d8f359619a94dec162326edbc985091f015f004f6a177fa828681fc23387", "pol": "5166e3a6c9908ffba918a399999c57ae67dfd66d6c2aee06023434e00e74ac5a", "sig": "X5O9P//oTqanG3TnRSMfi9OUS0HoJTRZfHm2gDvn2zG0n1+96oAyYtrHh7swDcufLOmk4Uh2fsWJkbw0xa8R/WlkdGj4pdKK1C1nmxFPnjwYuVoks26Ryom/cmjTZCYG/6+q2uwPK1+SvFo8UuQ756l5fEub5Pxjf9oT1SEnnL4LTSgrdZHU5qX5h8O81HJ1g4HIOR0bVf1GrKHufDMem9YGYIBmib5u9YziBLavoqHtmZ9b5AVIiyEW2Y/Hbtf9MJugoKJtg4arJaln3wrCq8SWjEP3PZrZdwr3bEKAy5fZNKmJAMZFcWo8N9G0vi/EoQmGXMtqk9aPaIQepoqIJg=="}, {"pcrs": [11], "pkfp": "8761d8f359619a94dec162326edbc985091f015f004f6a177fa828681fc23387", "pol": "33088bab63ad28d6bb89767f95bf367f2edc39c67e7272c3080d72c5b069fe6f", "sig": "Dx9H/HA+7+Wjo6uKT60dNvdmpLDt/omN154gRH3xKG5Xz1GOU/neVLtWFn9qJHeGqCxE/oROWBV5EhDndoZShkgxe8G157Z3Ul89qZjor0+sbp9kieq2ehr+us+XDdGLijWGTDmvOpqhmPG17GCJaOHMpWY6ReEyhAte4Y3bKhnG8cd5A8j9Mmc45kumMvyLBNkch15Vtna8MWfvLJODEblhYdSoIeDRh47mq6I+OPA/XSezXY3P0OouGpgMPI+QMJ6h0UPaKtNMw1BkzftTHmGK8ajIW/DoqAvqWQFcG7rpjzckASIOAOM6nZBYNYlQEWzNafUPsleiOYswtwdWBw=="}]}
.linux:
  size: 12286936 bytes
  sha256: 9c01c09edb51c80399d2d400649c5d81eed18d6bd46d3c37e356eb81a326d7e6
```

**Comment by AdrianVovk** [comment]
You can use systemd-pcrlock to parse the TPM event log and get a sequence of measurements that were performed. It'll at least give you an inkling of what unexpected measurement occurred, and when in the boot sequence it happened.

If that doesn't end up solving your issue please but that log here.

**Comment by jsommr** [comment]
This is what I get, both during initrd and when the system is booted:
```
/usr/lib/systemd/systemd-pcrlock log
Event log header has unexpected event type 0x00000007. (Probably not a TPM2 event log?)
```
But I can get the log this way:
```
tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements
```
Resulting in this chunk of data...
```
---
version: 1
events:
  PCRIndex: 0
  EventType: EV_S_CRTM_CONTENTS
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9d4c1a01ede1c71e1856ba852db202412e310a8b"
  EventSize: 27
  Event:
    BlobBase: 0x61754720746f6f42
    BlobLength: 0x757361654d206472
  PCRIndex: 0
  EventType: EV_S_CRTM_VERSION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "b9fb53c6d6cbeda6e6df25247938a305b800b539"
  EventSize: 14
  Event: "31002e0030002e00330031000000"
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "57cd4dc19442475aa82743484f3b1caa88e142b8"
  EventSize: 53
  Event:
    VariableName: 8be4df61-93ca-11d2-aa0d-00e098032b8c
    UnicodeNameLength: 10
    VariableDataLength: 1
    UnicodeName: SecureBoot
    VariableData: "00"
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9b1387306ebb7ff8e795e7be77563666bbf4516e"
  EventSize: 36
  Event:
    VariableName: 8be4df61-93ca-11d2-aa0d-00e098032b8c
    UnicodeNameLength: 2
    VariableDataLength: 0
    UnicodeName: PK
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9afa86c507419b8570c62167cb9486d9fc809758"
  EventSize: 38
  Event:
    VariableName: 8be4df61-93ca-11d2-aa0d-00e098032b8c
    UnicodeNameLength: 3
    VariableDataLength: 0
    UnicodeName: KEK
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "5bf8faa078d40ffbd03317c93398b01229a0e1e0"
  EventSize: 36
  Event:
    VariableName: d719b2cb-3d3a-4596-a3bc-dad00e67656f
    UnicodeNameLength: 2
    VariableDataLength: 0
    UnicodeName: db
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "ac34753044667647085e7b11910a0111129703f6"
  EventSize: 114
  Event:
    VariableName: d719b2cb-3d3a-4596-a3bc-dad00e67656f
    UnicodeNameLength: 3
    VariableDataLength: 76
    UnicodeName: dbx
    VariableData: "2616c4c14c509240aca941f9369343284c0000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  PCRIndex: 7
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 1
  EventType: EV_EFI_HANDOFF_TABLES
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "461cbe34f4defef4bea88ad454b1d32237428335"
  EventSize: 32
  Event: "01000000000000004415fdf294972c4a992ee5bbcf20e3940090028c00000000"
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "6f7db40fceba30cd6d39807fda9897a208751726"
  EventSize: 80
  Event:
    ImageLocationInMemory: 0x7b244018
    ImageLengthInMemory: 72200
    ImageLinkTimeAddress: 0x1000000
    LengthOfDevicePath: 48
    DevicePath: '010318000b00000000f0d47000000000ff9fe071000000000406140026ca1a82ea299349839f597fc021708d7fff0400'
  PCRIndex: 5
  EventType: EV_EFI_VARIABLE_BOOT
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9b99593353a610c4bee0d6a94a01a3296080c0fb"
  EventSize: 52
  Event:
    VariableName: 8be4df61-93ca-11d2-aa0d-00e098032b8c
    UnicodeNameLength: 9
    VariableDataLength: 2
    UnicodeName: BootOrder
    VariableData: "0200"
  PCRIndex: 5
  EventType: EV_EFI_VARIABLE_BOOT
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9bfe5e57ded99044b414b65ff93bbf27c3565548"
  EventSize: 144
  Event:
    VariableName: 8be4df61-93ca-11d2-aa0d-00e098032b8c
    UnicodeNameLength: 8
    VariableDataLength: 96
    UnicodeName: Boot0002
    VariableData: "010000004c00440065006200690061006e00000004012a000100000000080000000000000010020000000000e32fd2b4e26b0b4985e8b86beb01ce33020204041e005c007300680069006d007800360034002e0065006600690000007fff0400"
  PCRIndex: 5
  EventType: EV_EFI_ACTION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "cd0fdb4531a6ec41be2753ba042637d6e5f7f256"
  EventSize: 40
  Event: |-
    Calling EFI Application from Boot Option
  PCRIndex: 0
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 1
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 2
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 3
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 4
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 5
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 6
  EventType: EV_SEPARATOR
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9069ca78e7450a285173431b3e52c5c25299e473"
  EventSize: 4
  Event: "00000000"
  PCRIndex: 5
  EventType: EV_EFI_GPT_EVENT
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "e1dd0f143ec28281525352d54469bce23b6d7380"
  EventSize: 356
  Event: "4546492050415254000001005c000000e8ad470f000000000100000000000000ffbf4707000000002200000000000000debf47070000000028b2a97d882fd74589389a74ed84399d020000000000000080000000800000008f7ff87a020000000000000028732ac11ff8d211ba4b00a0c93ec93be32fd2b4e26b0b4985e8b86beb01ce330008000000000000ff170200000000000000000000000000450053005000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000af3dc60f838472478e793d69d8477de4c9a90da02ed24841a2a0979a2fbd468d0018020000000000ffb747070000000000000000000000007000720069006d0061007200790000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "abdb32d41bbc87f3586389ad1c732d3690fa776d"
  EventSize: 139
  Event:
    ImageLocationInMemory: 0x7b0a5018
    ImageLengthInMemory: 957136
    ImageLinkTimeAddress: 0x0
    LengthOfDevicePath: 107
    DevicePath: '02010c00d041030a0000000001010600041e0105080000000000031105000004012a000100000000080000000000000010020000000000e32fd2b4e26b0b4985e8b86beb01ce33020204041e005c007300680069006d007800360034002e0065006600690000007fff0400'
  PCRIndex: 14
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "e33f952d6cfc62f25b53ab92270b9883ed065cad"
  EventSize: 8
  Event:
    String: "MokList\0"
  PCRIndex: 14
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "d22c90e58e8c18e95b7c3314e0d670005ed009ce"
  EventSize: 9
  Event:
    String: "MokListX\0"
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_AUTHORITY
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "15875d39b8872f8aff3a92fc9f9e40ac75268e04"
  EventSize: 68
  Event:
    VariableName: 605dab50-e046-4300-abb6-3dd810dd8b23
    UnicodeNameLength: 9
    VariableDataLength: 18
    UnicodeName: SbatLevel
    VariableData: "736261742c312c323032313033303231380a"
  PCRIndex: 14
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "bf8b4530d8d246dd74ac53a13471bba17941dff7"
  EventSize: 15
  Event:
    String: "MokListTrusted\0"
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "1bd82a7de2842077eaa4b3ed66ea1b3ecad64e84"
  EventSize: 66
  Event:
    ImageLocationInMemory: 0x6d9dd018
    ImageLengthInMemory: 40376832
    ImageLinkTimeAddress: 0x14df90000
    LengthOfDevicePath: 34
    DevicePath: '04041e005c0067007200750062007800360034002e0065006600690000007fff0400'
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "f1a7ecb0cf7668e20d73177a1725b4d2aa4e5724"
  EventSize: 14
  Event:
    String: ".\0l\0i\0n\0u\0x\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "30046d8cce3f62554f32d69b005fa36c4d8a7e4a"
  EventSize: 14
  Event:
    String: ".\0l\0i\0n\0u\0x\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "93860b993799b71f0d0c34541e251ea0d6fc286c"
  EventSize: 14
  Event:
    String: ".\0o\0s\0r\0e\0l\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "472134f0367b35a15c409159f6dca8b73cfa2633"
  EventSize: 14
  Event:
    String: ".\0o\0s\0r\0e\0l\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "4ba066dbd5a063ff4a7d2deee4db04bdb70451cb"
  EventSize: 18
  Event:
    String: ".\0c\0m\0d\0l\0i\0n\0e\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "5dfcb23bc0af7ba29e160cd408214eb158049acf"
  EventSize: 18
  Event:
    String: ".\0c\0m\0d\0l\0i\0n\0e\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "cef6482ba7d6be694a6bed3411c3544214e984fd"
  EventSize: 16
  Event:
    String: ".\0i\0n\0i\0t\0r\0d\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "3d6435f6b54c1bc9f692374bc9e983c891b9a458"
  EventSize: 16
  Event:
    String: ".\0i\0n\0i\0t\0r\0d\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "72344ca1ba34b18d672055e30ce9fc1339fa9400"
  EventSize: 14
  Event:
    String: ".\0u\0n\0a\0m\0e\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "0895099cb96e0dbcd3e9055040fd57b329aacf7a"
  EventSize: 14
  Event:
    String: ".\0u\0n\0a\0m\0e\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "63af9d6ea7775d4cd2e43de708edebca019c6c1b"
  EventSize: 12
  Event:
    String: ".\0s\0b\0a\0t\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "edda907bc11330595f9d06bcc2a1362b1349474d"
  EventSize: 12
  Event:
    String: ".\0s\0b\0a\0t\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "000c51a54f37fccafef39b63155354d8c42fc60c"
  EventSize: 18
  Event:
    String: ".\0p\0c\0r\0p\0k\0e\0y\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "f05be4400973cef68832935de91bcbf16f73795a"
  EventSize: 18
  Event:
    String: ".\0p\0c\0r\0p\0k\0e\0y\0\0\0"
  PCRIndex: 4
  EventType: EV_EFI_BOOT_SERVICES_APPLICATION
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "9c5354690b8758903c965553b9f35c44ad51e8fb"
  EventSize: 56
  Event:
    ImageLocationInMemory: 0x6cdbf000
    ImageLengthInMemory: 12697600
    ImageLinkTimeAddress: 0x0
    LengthOfDevicePath: 24
    DevicePath: '04031400f8d1c555cd04b5468a20e56cbb3052d07fff0400'
  PCRIndex: 9
  EventType: EV_EVENT_TAG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "c9300880c684cb314dbf5efc25fecc37ae8c009d"
  EventSize: 34
  Event: "ed223b8f1a0000004c4f414445445f494d4147453a3a4c6f61644f7074696f6e7300"
  PCRIndex: 9
  EventType: EV_EVENT_TAG
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "ebadff6c3f46a7dabf28d88ac10cbd1755aa127a"
  EventSize: 21
  Event: "ec223b8f0d0000004c696e757820696e6974726400"
pcrs:
  sha1:
    0  : 0x72f58f4bb2d8f007bfbae3193aafc276b58b1eb9
    1  : 0x6564bd127905efa9c9f2ac1fc77a0ff48e7f4214
    2  : 0xb2a83b0ebf2f8374299a5b2bdfc31ea955ad7236
    3  : 0xb2a83b0ebf2f8374299a5b2bdfc31ea955ad7236
    4  : 0x891508d51ec253968182c4efff36281b391362c7
    5  : 0x77eefe6b6400283bb9ea3398a6c60d2c59ba5fce
    6  : 0xb2a83b0ebf2f8374299a5b2bdfc31ea955ad7236
    7  : 0xdd70faa576f6e836a012f7326205c928700872d8
    9  : 0x9ab6820b5836b09c0e5502ee805db6e9c7281450
    11 : 0xa44d9cb99fb01e36468dc6735b069871f8dee918
    14 : 0xfff865f8211b3e0625e0e22893a3ae76bc9d91bc
```
It's interesting how all the PCR 11 events happens twice, eg.:
```
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "f1a7ecb0cf7668e20d73177a1725b4d2aa4e5724"
  EventSize: 14
  Event:
    String: ".\0l\0i\0n\0u\0x\0\0\0"
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha1
    Digest: "30046d8cce3f62554f32d69b005fa36c4d8a7e4a"
  EventSize: 14
  Event:
    String: ".\0l\0i\0n\0u\0x\0\0\0"
```
