### ISSUE TITLE
ukify calculated hash mismatch with pcr11 values

### ISSUE THREAD

**Issue by sebo-b** [systemd/systemd#36502]
### systemd version the issue has been seen with

257.3-1

### Used distribution

Debian Trixie

### Linux kernel version used

6.12.12-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-analyze, systemd-stub

### Expected behaviour you didn't see

ukify --measure should report the same PCR11 values as seen during the boot process.

### Unexpected behaviour you saw

PCR11 values are different from those calculated by unify --measure. My assumption is that the stub extends PCR11 twice by section name instead of the section's content.

### Steps to reproduce the problem

I'm trying to implement TPM2-based root fs boot time unlocking for ZFS native encryption and values of PCR11 calculated by ukify --measure are different than observed.

```
root@server:~# ukify build --linux=/vmlinuz --initrd=/initrd.img --cmdline="root=zfs:tank/root initrd=initrd.img boot=zfs" --output=/boot/efi/debian.efi --signtool=sbsign --secureboot-private-key=DB.key --secureboot-certificate=DB.crt --measure --pcr-banks=sha256
+ sbverify --list /vmlinuz
Kernel version not specified, starting autodetection 😖.
Found uname version: 6.12.12-amd64
+ /usr/lib/systemd/systemd-measure calculate --osrel=/etc/os-release --cmdline=/tmp/tmp.cmdlineo_kwadfo --uname=/tmp/tmp.unamedwticfsv --linux=/vmlinuz --initrd=/initrd.img --sbat=/tmp/tmp.sbatjwf4bytw --bank=sha256
# PCR[11] Phase <enter-initrd>
11:sha256=5596db547598ca39c91585373c6613c9f27a8643211ed6db3dff9fdb08f7d0dc
# PCR[11] Phase <enter-initrd:leave-initrd>
11:sha256=0860a651e5bb1bb2a656065c819e0b995c03cf93c4ea1ea7d82a1d8692ea54bb
# PCR[11] Phase <enter-initrd:leave-initrd:sysinit>
11:sha256=b447e0cca09952364b5a11dd6fef70add153a74c0bdd669f993813eacf8c5f16
# PCR[11] Phase <enter-initrd:leave-initrd:sysinit:ready>
11:sha256=3c0d461c241077a8c1f255a53f67438e74c4f402ce59215f7fb9b17966809dd6
+ sbsign --key DB.key --cert DB.crt /tmp/ukivptprc_q --output /boot/efi/debian.efi
Enter PEM pass phrase:
Signing Unsigned original image
Wrote signed /boot/efi/debian.efi
```

```
root@server:~# ukify -j inspect /boot/efi/debian.efi
{
 ".sbat": {
 "size": 323,
 "sha256": "03314febb06169d71873605ea4919d0fe5fe2dd7ace9a097ce1cdd3983bd0254",
 "text": "sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md\nsystemd-stub,1,The systemd Developers,systemd,257,https://systemd.io/\nsystemd-stub.debian,1,Debian GNU/Linux,systemd,257.3-1,https://tracker.debian.org/pkg/systemd\nuki,1,UKI,uki,1,https://uapi-group.org/specifications/specs/unified_kernel_image/\n\u0000"
 },
 ".osrel": {
 "size": 222,
 "sha256": "d233f3430906f91316821d805531cf09fd0d5dad628a89a40e56bc65301c0ca7",
 "text": "PRETTY_NAME=\"Debian GNU/Linux trixie/sid\"\nNAME=\"Debian GNU/Linux\"\nVERSION_CODENAME=trixie\nID=debian\nHOME_URL=\"https://www.debian.org/\"\nSUPPORT_URL=\"https://www.debian.org/support\"\nBUG_REPORT_URL=\"https://bugs.debian.org/\"\n"
 },
 ".cmdline": {
 "size": 45,
 "sha256": "f014336109f1063f63f0ba6a264f1460295252777770b248be0207e6c5b586e4",
 "text": "root=zfs:tank/root initrd=initrd.img boot=zfs"
 },
 ".uname": {
 "size": 13,
 "sha256": "7e6c368215aa5f4ada5bf081667863cad6f1271184407c49dabc1798425a2cf2",
 "text": "6.12.12-amd64"
 },
 ".linux": {
 "size": 10041280,
 "sha256": "ad9e141335157357ed79a8dad698f2706cf6eb2bc615d97a87d0fc0e272196f7"
 },
 ".initrd": {
 "size": 46417938,
 "sha256": "bdbab2fb81ab80e2dacba6b3b17bf01d809c94a7803d70eefd2d6ac92ee82af3"
 }
```

Reboot into initramfs:
```
BusyBox u1.37.0 (Debian 1:1.37.0-4) built-in shell (ash)
Enter 'help' for a list of built-in commands.
(initramfs) tpm2_pcrread sha256:11
sha256:
(initramfs)
11: 0xE4D6672D08F73D0AAE45269E601BF1231D40945D3505E9A4B44141DD5B50E600
```

Boot full system:
```
root@server:~# tpm2_pcrread sha256:11
 sha256:
 11: 0xA3FBB541FAD234BE01AF6ACFF99676316B586E3FE832AB1E6A38F85CA182CF1E

root@server:~# systemd-analyze pcrs 11
NR NAME SHA256 
11 kernel-boot a3fbb541fad234be01af6acff99676316b586e3fe832ab1e6a38f85ca182cf1e 
```

```
root@server:~# /usr/lib/systemd/systemd-pcrlock lock-uki /boot/efi/debian.efi |jq '.records[] | select(.pcr == 11) | .digests[] | select(.hashAlg == "sha256")'

{
 "hashAlg": "sha256",
 "digest": "0da293e37ad5511c59be47993769aacb91b243f7d010288e118dc90e95aaef5a"
}
{
 "hashAlg": "sha256",
 "digest": "ad9e141335157357ed79a8dad698f2706cf6eb2bc615d97a87d0fc0e272196f7"
}
{
 "hashAlg": "sha256",
 "digest": "3fb9e4e3cc810d4326b5c13cef18aee1f9df8c5f4f7f5b96665724fa3b846e08"
}
{
 "hashAlg": "sha256",
 "digest": "d233f3430906f91316821d805531cf09fd0d5dad628a89a40e56bc65301c0ca7"
}
{
 "hashAlg": "sha256",
 "digest": "461203a89f23e36c3a4dc817f905b00484d2cf7e7d9376f13df91c41d84abe46"
}
{
 "hashAlg": "sha256",
 "digest": "f014336109f1063f63f0ba6a264f1460295252777770b248be0207e6c5b586e4"
}
{
 "hashAlg": "sha256",
 "digest": "15ee37e75f1e8d42080e91fdbbd2560780918c81fe3687ae6d15c472bbdaac75"
}
{
 "hashAlg": "sha256",
 "digest": "bdbab2fb81ab80e2dacba6b3b17bf01d809c94a7803d70eefd2d6ac92ee82af3"
}
{
 "hashAlg": "sha256",
 "digest": "da7a6d941caa9d28b8a3665c4865c143db8f99400ac88d883370ae3021636c30"
}
{
 "hashAlg": "sha256",
 "digest": "7e6c368215aa5f4ada5bf081667863cad6f1271184407c49dabc1798425a2cf2"
}
{
 "hashAlg": "sha256",
 "digest": "ff552fd255be18a3d61c0da88976fc71559d13aad12d1dfe1708cf950cc4b74c"
}
{
 "hashAlg": "sha256",
 "digest": "03314febb06169d71873605ea4919d0fe5fe2dd7ace9a097ce1cdd3983bd0254"
}
```

```
root@server:~# tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements
--- 
version: 1 
events: 
(...) 
- EventNum: 27 
  PCRIndex: 11 
  EventType: EV_IPL 
  DigestCount: 1 
  Digests: 
  - AlgorithmId: sha256 
    Digest: "0da293e37ad5511c59be47993769aacb91b243f7d010288e118dc90e95aaef5a" 
  EventSize: 14 
  Event: 
    String: ".\0l\0i\0n\0u\0x\0\0\0" 
- EventNum: 28 
  PCRIndex: 11 
  EventType: EV_IPL 
  DigestCount: 1 
  Digests:
  - AlgorithmId: sha256
    Digest: "ad9e141335157357ed79a8dad698f2706cf6eb2bc615d97a87d0fc0e272196f7"
  EventSize: 14
  Event:
    String: ".\0l\0i\0n\0u\0x\0\0\0"
- EventNum: 29
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "3fb9e4e3cc810d4326b5c13cef18aee1f9df8c5f4f7f5b96665724fa3b846e08"
  EventSize: 14
  Event:
    String: ".\0o\0s\0r\0e\0l\0\0\0"
- EventNum: 30
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "d233f3430906f91316821d805531cf09fd0d5dad628a89a40e56bc65301c0ca7"
  EventSize: 14
  Event:
    String: ".\0o\0s\0r\0e\0l\0\0\0"
- EventNum: 31
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "461203a89f23e36c3a4dc817f905b00484d2cf7e7d9376f13df91c41d84abe46"
  EventSize: 18
  Event:
    String: ".\0c\0m\0d\0l\0i\0n\0e\0\0\0"
- EventNum: 32
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "f014336109f1063f63f0ba6a264f1460295252777770b248be0207e6c5b586e4"
  EventSize: 18
  Event:
    String: ".\0c\0m\0d\0l\0i\0n\0e\0\0\0"
- EventNum: 33
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "15ee37e75f1e8d42080e91fdbbd2560780918c81fe3687ae6d15c472bbdaac75"
  EventSize: 16
  Event:
    String: ".\0i\0n\0i\0t\0r\0d\0\0\0"
- EventNum: 34
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "bdbab2fb81ab80e2dacba6b3b17bf01d809c94a7803d70eefd2d6ac92ee82af3"
  EventSize: 16
  Event:
    String: ".\0i\0n\0i\0t\0r\0d\0\0\0"
- EventNum: 35
  PCRIndex: 11
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "da7a6d941caa9d28b8a3665c4865c143db8f99400ac88d883370ae3021636c30"
  EventSize: 14
  Event:
    String: ".\0u\0n\0a\0m\0e\0\0\0"
- EventNum: 36
 PCRIndex: 11
 EventType: EV_IPL
 DigestCount: 1
 Digests:
 - AlgorithmId: sha256
   Digest: "7e6c368215aa5f4ada5bf081667863cad6f1271184407c49dabc1798425a2cf2"
 EventSize: 14
 Event:
    String: ".\0u\0n\0a\0m\0e\0\0\0"
- EventNum: 37
 PCRIndex: 11
 EventType: EV_IPL
 DigestCount: 1
 Digests:
 - AlgorithmId: sha256
   Digest: "ff552fd255be18a3d61c0da88976fc71559d13aad12d1dfe1708cf950cc4b74c"
 EventSize: 12
 Event:
    String: ".\0s\0b\0a\0t\0\0\0"
- EventNum: 38
 PCRIndex: 11
 EventType: EV_IPL
 DigestCount: 1
 Digests:
 - AlgorithmId: sha256
   Digest: "03314febb06169d71873605ea4919d0fe5fe2dd7ace9a097ce1cdd3983bd0254"
 EventSize: 12
 Event:
    String: ".\0s\0b\0a\0t\0\0\0"
(...)
pcrs:
 sha256:
 11 : 0xe4d6672d08f73d0aae45269e601bf1231d40945d3505e9a4b44141dd5b50e600
```

```
PCR   PCRNAME            EVENT                         MATCH SHA256                                                           F/U COMPONENT                         DESCRIPTION
(...)
 11 █ kernel-boot        ipl                               ✓ 0da293e37ad5511c59be47993769aacb91b243f7d010288e118dc90e95aaef5a F   -                                 String: .linux
 11 █ kernel-boot        ipl                               - ad9e141335157357ed79a8dad698f2706cf6eb2bc615d97a87d0fc0e272196f7 F   -                                 String: .linux
 11 █ kernel-boot        ipl                               ✓ 3fb9e4e3cc810d4326b5c13cef18aee1f9df8c5f4f7f5b96665724fa3b846e08 F   -                                 String: .osrel
 11 █ kernel-boot        ipl                               - d233f3430906f91316821d805531cf09fd0d5dad628a89a40e56bc65301c0ca7 F   -                                 String: .osrel
 11 █ kernel-boot        ipl                               ✓ 461203a89f23e36c3a4dc817f905b00484d2cf7e7d9376f13df91c41d84abe46 F   -                                 String: .cmdline
 11 █ kernel-boot        ipl                               - f014336109f1063f63f0ba6a264f1460295252777770b248be0207e6c5b586e4 F   -                                 String: .cmdline
 11 █ kernel-boot        ipl                               ✓ 15ee37e75f1e8d42080e91fdbbd2560780918c81fe3687ae6d15c472bbdaac75 F   -                                 String: .initrd
 11 █ kernel-boot        ipl                               - bdbab2fb81ab80e2dacba6b3b17bf01d809c94a7803d70eefd2d6ac92ee82af3 F   -                                 String: .initrd
 11 █ kernel-boot        ipl                               ✓ da7a6d941caa9d28b8a3665c4865c143db8f99400ac88d883370ae3021636c30 F   -                                 String: .uname
 11 █ kernel-boot        ipl                               - 7e6c368215aa5f4ada5bf081667863cad6f1271184407c49dabc1798425a2cf2 F   -                                 String: .uname
 11 █ kernel-boot        ipl                               ✓ ff552fd255be18a3d61c0da88976fc71559d13aad12d1dfe1708cf950cc4b74c F   -                                 String: .sbat
 11 █ kernel-boot        ipl                               - 03314febb06169d71873605ea4919d0fe5fe2dd7ace9a097ce1cdd3983bd0254 F   -                                 String: .sbat
(...)
 11 █ kernel-boot        phase                             ✓ 730bb5a583ba880c277e656d2dc8aba1a314a11b14d25b05153d2bab82567a48 U   850-sysinit                       sysinit
 11 █ kernel-boot        phase                             ✓ b24d6d33736ecd5604a4b17bc9c6481039fac362bb7df044ef1c10a2bfd21db6 U   900-ready                         ready

PCR     PCRNAME             COUNT H R C CALCULATED SHA256                                                OBSERVED SHA256
 11 █ 😨 kernel-boot            14 ✓ ✗ ✗ a3fbb541fad234be01af6acff99676316b586e3fe832ab1e6a38f85ca182cf1e a3fbb541fad234be01af6acff99676316b586e3fe832ab1e6a38f85ca182cf1e
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh

```
